config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'

  resources :messages do
    member do
      get :mark_as_read
      get :mark_as_unread
      post :reply
    end
  end

  resources :drafts do
    member do
      get :send_mail
    end
  end

  resources :files, only: :show
  resources :folders, only: :show

  get '/auth/microsoft_office365/callback', to: 'office365#callback', as: :office365_callback
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :nylas

  def nylas
    @nylas ||= nylas_client(ENV['ACCOUNT_ACCESS_TOKEN'])
  end

  def nylas_client(token)
    @nylas_client = Nylas::API.new(
      app_id: ENV['NYLAS_CLIENT_ID'],
      app_secret: ENV['NYLAS_CLIENT_SECRET'],
      access_token: token
    )
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: %i[send_mail]

  def index
    @drafts = nylas.drafts
  end

  def send_mail
    @draft.send!

    redirect_to folder_path(@draft.folder.id)
  end

  private

  def set_draft
    @draft ||= nylas.drafts.find(params[:id])
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :set_file, only: %i[show destroy mark_as_read mark_as_unread ]

  layout false

  def show
    @file.download
    send_file @file.file, filename: @file.filename, type: @file.content_type
  end

  private

  def set_file
    @file ||= nylas.files.find(params[:id])
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder

  def show
    @messages = nylas.messages.where(in: params[:id])
  end

  private

  def set_folder
    @folder ||= nylas.folders.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message,
                only: %i[show destroy mark_as_read mark_as_unread reply]

  def index
    @messages = nylas.messages
  end

  def show; end

  def mark_as_read
    @message.update(unread: false)

    redirect_to root_path
  end

  def mark_as_unread
    @message.update(unread: true)

    redirect_to root_path
  end

  def reply
    message = @message.to_h
    @draft = nylas.drafts.create(
      from: message[:to],
      to: message[:from],
      reply_to_message_id: message[:id],
      subject: params[:subject],
      body: params[:body]
    )
    @draft.send!

    flash[:success] = 'Reply Sent'
    redirect_to message_path(@message.id)
  end

  private

  def set_message
    @message ||= nylas.messages.find(params[:id])
  end
end

app/controllers/office365_controller.rb
class Office365Controller < ApplicationController
  def callback
    auth_hash = request.env['omniauth.auth']

    nylas_token = nylas.authenticate(
      name: auth_hash['info']['display_name'],
      email_address: auth_hash['info']['email'],
      provider: :office365,
      settings: {
        microsoft_client_id: ENV['OFFICE_365_ID'],
        microsoft_client_secret: ENV['OFFICE_365_SECRET'],
        microsoft_refresh_token: auth_hash['credentials']['refresh_token'],
        redirect_uri: office365_callback_url
      },
      scopes: 'email.modify,email.send,email.folders_and_labels,email.drafts,calendar,contacts'
    )

    render json: nylas_token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drafts/index.html.haml
%table.table{style: "width:100%"}
  %thead
    %tr
      %th ID / Thread ID
      %th From / To
      %th Date
      %th Subject
      %th Snippet
      %th Actions
  %tbody
    - @drafts.each do |msg|
      %tr
        %td
          = msg.id
          = msg.thread_id
        %td
          - msg.from.each do |from|
            .badge.badge-success
              = from.name
              %br
              = from.email
          %br
          - msg.to.map(&:email).each do |email|
            .badge.badge-default= email
        %td
          = msg.date.to_datetime.strftime('%Y-%m-%d')
          = msg.date.to_datetime.strftime('%H:%M:%S')
        %td= link_to msg.subject, message_path(msg.id)
        %td= msg.snippet
        %td
          = link_to 'Send Mail', send_mail_draft_path(msg.id)

app/views/folders/show.html.haml
%h4= @folder.display_name
- drafts = @folder.display_name.eql?('Drafts')
- inbox = @folder.display_name.eql?('Inbox')
%table.table{style: "width:100%"}
  %thead
    %tr
      %th ID / Thread ID
      %th From / To
      %th Date
      %th Subject
      %th Snippet
      - if inbox || drafts
        %th Actions
  %tbody
    - @messages.each do |msg|
      %tr
        %td
          = msg.id
          %br
          = msg.thread_id
        %td
          - msg.from.each do |from|
            .badge.badge-success
              = from.name
              %br
              = from.email
          %br
          - msg.to.map(&:email).each do |email|
            .badge.badge-default= email
        %td
          = msg.date.to_datetime.strftime('%Y-%m-%d')
          = msg.date.to_datetime.strftime('%H:%M:%S')
        %td= link_to msg.subject, message_path(msg.id)
        %td= msg.snippet
        %td
          - if drafts
            = link_to 'Send Mail', send_mail_draft_path(msg.id)
          - if inbox
            - if msg.unread
              = link_to 'Mark as Read', mark_as_read_message_path(msg.id)
            - else
              = link_to 'Mark as Unread', mark_as_unread_message_path(msg.id)

app/views/layouts/_sidebar.html.haml
.sidebar
  %a{href: root_path}
    %h5 NylasDemo
  - nylas.folders.each do |folder|
    %a{href: folder_path(folder.id)}= folder.display_name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NylasDemo
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('favicon.ico')
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", rel: "stylesheet"}
    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css", rel: "stylesheet"}
    %script{crossorigin: "anonymous", integrity: "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", src: "https://code.jquery.com/jquery-3.4.1.slim.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", src: "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/sidebar'
    .content
      .container-fluid
        = yield

app/views/messages/_message_details.html.haml
%h4 Details
ID :
= message.id
%br

Thread ID :
= message.thread_id
%br

Starred :
= message.starred
%br

Unread :
= message.unread
%br

To Email :
= message.to.map(&:email).join('\n')
%br

From Email :
= message.from.map{ |from| "#{from.name} <#{from.email}>" }.join('\n')
%br

Date :
= message.date.to_datetime
%br

Subject :
= message.subject
%br

Snippet :
= message.snippet
%br

Files :
- message.files.each do |file|
  = link_to file.filename, file_path(file.id), target: '_blank'
%br

Body :
= message.body.html_safe
%br

app/views/messages/_reply_form.html.haml
%h4 Reply
= form_with(url: reply_message_path) do |f|
  .form-group
    = f.label :subject, class: 'label-control'
    = f.text_field :subject, class: 'form-control', value: "Re: #{message.subject}"
  .form-group
    = f.label :body, class: 'label-control'
    = f.text_area :body, class: 'form-control', rows: 5
  %br
  = submit_tag 'Send Reply', class: 'btn btn-sm btn-primary'

app/views/messages/index.html.haml
%table{style: "width:100%"}
  %thead
    %tr
      %th ID
      %th Thread ID
      %th To Email
      %th From Email
      %th Date
      %th Subject
      %th Snippet
      %th Starred
      %th Unread
  %tbody
    - @messages.each do |msg|
      %tr
        %td= msg.id
        %td= msg.thread_id
        %td= msg.to.map(&:email).join('\n')
        %td= msg.from.map{ |from| "#{from.name} <#{from.email}>" }.join('\n')
        %td= msg.date.to_datetime
        %td= link_to msg.subject, message_path(msg.id)
        %td= msg.snippet
        %td= msg.starred
        %td
          - if msg.unread
            = link_to 'Mark as Read', mark_as_read_message_path(msg.id)
          - else
            = link_to 'Mark as Unread', mark_as_unread_message_path(msg.id)

app/views/messages/show.html.haml
.row
  .col-md-1
  .col-md-5.col-sm-12
    = render 'message_details', message: @message
  .col-md-5.col-sm-12
    = render 'reply_form', message: @message